package com.marcondino.notes;

import androidx.room.Database;
import androidx.room.RoomDatabase;

@Database(entities = {Note.class}, version = 1,exportSchema = false)
public abstract class NoteDatabase extends RoomDatabase {
    public abstract NoteDao noteDao();
    // The reason that this is abstract is because this Room library, when you're compiling these files,
    // it's going to generate some code for us. And the class that implements, or extends, this abstract
    // class is going to be generated by the Room library.
}
